backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "Madelon ter Borg"
    label: "Werken"
    folder: "content/werken"
    create: true
    slug: "{{year}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "titel", widget: "string" }
      - {
          label: "Jaar",
          name: "jaar",
          widget: "datetime",
          default: "{{now}}",
          dateformat: "YYYY",
        }
      - { label: "Medium", name: "medium", widget: "string" }
      - { label: "Beschrijving", name: "beschrijving", widget: "markdown" }
      - { label: "Link", name: "link", widget: "text", required: false }
  - name: "Pagina's"
    label: "pagina's"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "text" }
          - {
              label: "Section",
              name: "section",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: "string" },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
      - file: "content/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }
